### ISSUE TITLE
Documentation to use id

### ISSUE THREAD

**Issue by white-gecko** [simeonackermann/RDForm#1]
In https://github.com/simeonackermann/RDForm#classes you are describing the attribute `id=`: “Optional class ID to reference classes with same typeof”. But there is not usage example. Could you maybe give an example, how to reference an `id=`?

**Comment by simeonackermann** [comment]
Its easy, just do it as you reference the typeof attribute. I added an example under: https://github.com/simeonackermann/RDForm#class-resources
