### ISSUE TITLE
Select Options for Resources

### ISSUE THREAD

**Issue by white-gecko** [simeonackermann/RDForm#14]
In the README there is the example of an HTML select element with literal values as options. Is it also possible to predefine a list of IRI resources for a select element? (Without using a SPARQL endpoint for the options.)

    <input name="foaf:gender" type="literal" select select-options='{"woman":"woman", "man":"man"}' datatype="xsd:string" />

**Comment by simeonackermann** [comment]
With latest commits its possible to define a select list for IRIs like following:

```html
<input name="foaf:knows" type="resource" select select-options='{"ex:p1":"Person 1", "ex:p2":"Person 2"}' external />
```

**Comment by white-gecko** [comment]
Thank you very much.
