### ISSUE TITLE
cascaded links 

### ISSUE THREAD

**Issue by marlux** [simeonackermann/RDForm#2]
I got a problem with following template:

```
<legend>Grandchild</legend>
<div typeof="n0:Person"  id="Grandchild">
<label>Ancestor</label>
<input name="n0:ancestor" type="resource"  value="Parent"  >
</div>
<legend>Parent</legend>
<div typeof="n0:Person"  id="Parent">
<label>Ancestor</label>
<input name="n0:ancestor" type="resource"  value="Grandparent"  >
</div>
<legend>Grandparent</legend>
<div typeof="n0:Person"  id="Grandparent">
<label>Age</label>
<input name="n0:age" type="literal" >
</div>
```

The result is following:

![rdfform](https://cloud.githubusercontent.com/assets/7299287/8373525/f3c048ae-1bed-11e5-931e-b59349565bf8.png)

The Legend of Parent is lost. Now it is an Grandparent. The type of the last <div> block is not correct.
Also the legend in the last <div> is lost too.

**Comment by simeonackermann** [comment]
Thanks for reporting. You are right, there is this issue with such links.

Please checkout the latest commits, it should work now. And dont forget to give your classes the attribute "resource" for the resource URI, otherwise it even wont work.
