### ISSUE TITLE
Add button in a type="resource" input

### ISSUE THREAD

**Issue by cfrancois7** [simeonackermann/RDForm#7]
Hello,

I tried the RDForm. It's very interesting.
However, I didn't success to get more than one instance for the "resource" type input even when I use "additional multiple". The problem occurs for every template. However, for the other type, the "additional multiple" option works well.
Is it normal? Did I forget something?

![capture d ecran 2016-07-20 a 17 52 20](https://cloud.githubusercontent.com/assets/11422336/16993254/dd59b062-4ea2-11e6-8f28-9f47cc42b992.png)

**Comment by simeonackermann** [comment]
Normally this should also work for "resource", but it doesn't for me too. I'll have a look at the code...

**Comment by simeonackermann** [comment]
Sould solved with 01bbfd31677b44047ce096e3505d6f8a83555874

**Comment by cfrancois7** [comment]
Thanks a lot. I confirm that works fine.

**Comment by cfrancois7** [comment]
I come back regarding this problem.
I tried to use the multiple option inside a type "resource" input.

The idea here is to link several representative country on the location.
How can I reproduce the previous correction to this level?

The symptom is similar to the previous bug.
![capture d ecran 2016-07-21 a 12 47 08](https://cloud.githubusercontent.com/assets/11422336/17020341/45135160-4f41-11e6-8cbf-84ae25da999d.png)

**Comment by cfrancois7** [comment]
More specifically the previous correction seems to disable the "add" function inside the input. For instance, the button "add" for the e-mail from the `form.html` template doesn't work now.

**Comment by simeonackermann** [comment]
Ok, this should work again after too motivated fixing... ;)

**Comment by cfrancois7** [comment]
Perfect !! I confirm that works well.
Thanks you again.
