### ISSUE TITLE
How to use multiple wildcards

### ISSUE THREAD

**Issue by andrefilipemb** [simeonackermann/RDForm#8]
Hi,

I would like to know if it is possible to use multiple wildcards for field replacement. For example:
<label> Label name </label>
<input name="dct:label" type="literal" datatype="xsd:string"/ value="{wildcard1}/{wildcard2}/{wildcard3}">

Another question:
I would like to use the parent resourceId in the child resource.  Is it possible?
For example:
PARENT:
< div typeof="dcat:Dataset" resource="http://vera.wds.poli.usp.br/{pid}/{dct:label}">

< input name="dcat:contactPoint" type="resource" value="dcat:contactPoint" ....
< /div>

CHILD:
< div typeOf="dcat:contactPoint" resource="http://trial.com/{pid}/{did}/contact/{vcard:hasEmail}">
< label>Parent Resource ID</label>
< input name="dct:identifier"  type="literal"  value="HERE GOES PARENT RESOURCE ID" />
< /div>

Thanks a lot.

**Comment by simeonackermann** [comment]
Both is possible.

Multiple wildcards can be used just like you want.

To use values from a parent form, the wildcard reference has to pass with the `arguments` attribute. For example:
```html
<div typeof="foaf:Person" resource="Person-{pid}">
	<input name="pid" type="hidden" value="123-{foaf:name}" />

       <label>Name</label>
       <input name="foaf:name" type="literal" datatype="xsd:string" required />

	<input name="bio:event" type="resource" value="bio:Birth"
	arguments='{"pid":"{pid}"}' 
	/>
</div>

<div typeof="bio:Birth" resource="Birth-{pid}">
	<input name="dc:date" type="literal" datatype="xsd:date" placeholder="JJJJ-MM-TT" />
</div>
```

**Comment by simeonackermann** [comment]
I close this issue because of its age...
